version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: loan-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loan_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: loan_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    platform: linux/arm64
    build:
      context: ./loan-backend
    container_name: loan-backend
    ports:
      - "8000:8000"
    volumes:
      - ./loan-backend:/var/www
    working_dir: /var/www
    command: >
      sh -c "./wait-for-db.sh db:3306 -- 
      php artisan config:clear &&
      php artisan migrate --seed &&
      php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db


  frontend:
    platform: linux/arm64
    build:
      context: ./loan-frontend
    container_name: loan-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./loan-frontend:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  db_data:
